### PR TITLE
Display unit test coverage on Codecov.io

### LINKED ISSUE #29: Register this repository on Codecov.io and make sure the code coverage report is sent to Codecov
Register this repository on Codecov.io and make sure the code coverage report is sent to Codecov

### PR DESCRIPTION
**Pull request by tisnik**
# Description

Register this repository on Codecov.io and make sure the code coverage report is sent to Codecov

Fixes #29

## Type of change

- [x] New feature (non-breaking change which adds functionality)

### CODE REVIEW

**Comment by tisnik** [comment]
[test]

**Comment by tisnik** [comment]
[test]

**Comment by tisnik** [comment]
[test]

**Comment by tisnik** [comment]
[test]

**Review by natiiix — APPROVED** [review]

**Pull request merged**
