### PR TITLE
introduce versioning for scoring golang packages

### PR DESCRIPTION
**Pull request by miteshvp**

### CODE REVIEW

**Comment by rootAvish** [comment]
Is this tested? I don't remember the code exactly but seems like the push and pull locations are different.

**Comment by miteshvp** [comment]
@rootAvish - Push is always ahead of Pull in our case. 
1.  Scoring is already happening based on `day-01`.
2. After training is completed, Push happens with `day-02`.  
3. Now, if we are confident with new model `day-02` then we create saas-analytics PR to score (pull) based on `day-02`. 

Hope it helps.

**Review by rootAvish — APPROVED** [review]
I understand, LGTM then.

**Comment by miteshvp** [comment]
Let's test this on stage

**Pull request merged**
